sudo: required

language: go

go:
  - 1.3

env:
  global:
    - ORACLE_INSTANTCLIENT_FILE=oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm
    - ORACLE_INSTANTCLIENT_SDK_FILE=oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm

before_install:
  - .travis/oracle-instantclient/download_instantclient.sh
  - .travis/oracle-instantclient/install_instantclient.sh